package fantasticfour.magiceight;

public enum Magic8Status {
    ADD_INPUT_MISMATCH,
    DELETE_INPUT_MISMATCH,
    DISPLAY_INPUT_MISMTACH,
    EDIT_INPUT_MISMATCH,
    EXIT_INPUT_MISMATCH,
    HELP_INPUT_MISMATCH,
    OPEN_INPUT_MISMATCH,
    SEARCH_INPUT_MISMATCH,
    UNDO_INPUT_MISMATCH,
    REDO_INPUT_MISMATCH,
    
    ADD_SUCCESS,
    DELETE_SUCCESS,
    DISPLAY_SUCCESS,
    EDIT_SUCCESS,
    EXIT_SUCCESS,
    HELP_SUCCESS,
    OPEN_SUCCESS,
    SEARCH_SUCCESS,
    UNDO_SUCCESS,
    REDO_SUCCESS
}
